### ISSUE TITLE
Your other bot that is linked in the description.

### ISSUE THREAD

**Issue by KeenanPayne504** [Baronjohn/MudaeHelper#1]
Hello was just wondering, did you remove discontinue your other bot for autoclaim/wishing? I also noticed the version int he preview image is different.

**Comment by Baronjohn** [comment]
There was no other bot from me. I forked another project some time ago, but didn´t quite get it to work. So I started devoloping my own solution. This is the main bot for rolling automated in mudae, while the linked project is the discord bot component, which enables you to use the autoclaim/Kakerareact features of Mainprogram. 

However it isn´t quite finished yet, because autoreacting and stuff like that is still with fixed coords for my setup. I will change this in the future.

**Comment by KeenanPayne504** [comment]
Oh I see. Thanks for the reply, I understand now.
